/**
 * Demo Project: Invoice Processing Automation
 * 
 * This demo showcases a comprehensive automation use case for accounts payable
 * invoice processing, demonstrating all features of the AgentPrep platform.
 */

export const invoiceProcessingDemo = {
  useCase: {
    name: 'Invoice Processing Automation',
    objective: 'Automate the end-to-end accounts payable invoice processing workflow to reduce manual effort, improve accuracy, and accelerate payment cycles',
    scope: 'Covers invoice receipt, validation, approval routing, payment processing, and exception handling for vendor invoices across all business units',
    sponsor: 'Sarah Chen, VP of Finance',
    priority: 'high',
    status: 'draft',
    tags: ['finance', 'accounts-payable', 'automation', 'rpa', 'ocr'],
  },
  
  process: {
    roles: [
      {
        id: 'role-ap-clerk',
        name: 'AP Clerk',
        type: 'human',
        description: 'Handles exception cases and oversees automated processing',
      },
      {
        id: 'role-accountant',
        name: 'Accountant',
        type: 'human',
        description: 'Reviews and approves invoices over threshold amounts',
      },
      {
        id: 'role-system',
        name: 'Automation System',
        type: 'agent',
        description: 'AI agent that performs automated invoice processing tasks',
      },
    ],
    
    steps: [
      {
        id: 'step-1',
        parent_id: null,
        title: 'Receive Invoice',
        description: 'Invoice arrives via email or vendor portal',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 0,
        order_index: 0,
        metadata: { automated: true, duration_minutes: 1 },
      },
      {
        id: 'step-2',
        parent_id: null,
        title: 'Extract Invoice Data',
        description: 'Use OCR and AI to extract invoice header and line items',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 0,
        order_index: 1,
        metadata: { automated: true, duration_minutes: 2, technology: 'OCR, NLP' },
      },
      {
        id: 'step-3',
        parent_id: null,
        title: 'Validate Invoice Data',
        description: 'Perform validation checks on extracted data',
        type: 'decision',
        role: 'Automation System',
        role_id: 'role-system',
        level: 0,
        order_index: 2,
        metadata: { automated: true, duration_minutes: 1 },
      },
      {
        id: 'step-3-1',
        parent_id: 'step-3',
        title: 'Check PO Match',
        description: 'Verify invoice matches purchase order in ERP system',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 1,
        order_index: 0,
        metadata: { automated: true },
      },
      {
        id: 'step-3-2',
        parent_id: 'step-3',
        title: 'Verify Vendor Details',
        description: 'Confirm vendor is registered and active in master data',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 1,
        order_index: 1,
        metadata: { automated: true },
      },
      {
        id: 'step-3-3',
        parent_id: 'step-3',
        title: 'Validate Amounts',
        description: 'Check invoice amounts against tolerances and PO',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 1,
        order_index: 2,
        metadata: { automated: true },
      },
      {
        id: 'step-4',
        parent_id: null,
        title: 'Route for Approval',
        description: 'Determine approval path based on amount and department',
        type: 'decision',
        role: 'Automation System',
        role_id: 'role-system',
        level: 0,
        order_index: 3,
        metadata: { automated: true, duration_minutes: 1 },
      },
      {
        id: 'step-5',
        parent_id: null,
        title: 'Approve Invoice',
        description: 'Accountant reviews and approves invoice',
        type: 'task',
        role: 'Accountant',
        role_id: 'role-accountant',
        level: 0,
        order_index: 4,
        metadata: { automated: false, duration_minutes: 5 },
      },
      {
        id: 'step-6',
        parent_id: null,
        title: 'Post to ERP',
        description: 'Create accounting entry in ERP system',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 0,
        order_index: 5,
        metadata: { automated: true, duration_minutes: 1 },
      },
      {
        id: 'step-7',
        parent_id: null,
        title: 'Schedule Payment',
        description: 'Add to payment batch based on terms and due date',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 0,
        order_index: 6,
        metadata: { automated: true, duration_minutes: 1 },
      },
      {
        id: 'step-8',
        parent_id: null,
        title: 'Handle Exceptions',
        description: 'Route validation failures to AP clerk for resolution',
        type: 'task',
        role: 'AP Clerk',
        role_id: 'role-ap-clerk',
        level: 0,
        order_index: 7,
        metadata: { automated: false, duration_minutes: 15, exception_rate: 0.15 },
      },
      {
        id: 'step-9',
        parent_id: null,
        title: 'Archive Documents',
        description: 'Store invoice and supporting documents in document management system',
        type: 'task',
        role: 'Automation System',
        role_id: 'role-system',
        level: 0,
        order_index: 8,
        metadata: { automated: true, duration_minutes: 1 },
      },
    ],
  },
  
  dataAssets: [
    {
      id: 'data-1',
      name: 'Invoice Master',
      system: 'SAP ERP',
      object_type: 'table',
      has_pii: false,
      quality_score: 4,
      fields: [
        { name: 'invoice_id', type: 'string', required: true },
        { name: 'vendor_id', type: 'string', required: true },
        { name: 'invoice_date', type: 'date', required: true },
        { name: 'due_date', type: 'date', required: true },
        { name: 'amount', type: 'decimal', required: true },
        { name: 'currency', type: 'string', required: true },
        { name: 'status', type: 'string', required: true },
      ],
      metadata: { record_count: 250000, update_frequency: 'real-time' },
    },
    {
      id: 'data-2',
      name: 'Purchase Orders',
      system: 'SAP ERP',
      object_type: 'table',
      has_pii: false,
      quality_score: 5,
      fields: [
        { name: 'po_number', type: 'string', required: true },
        { name: 'vendor_id', type: 'string', required: true },
        { name: 'po_date', type: 'date', required: true },
        { name: 'total_amount', type: 'decimal', required: true },
        { name: 'status', type: 'string', required: true },
      ],
      metadata: { record_count: 180000 },
    },
    {
      id: 'data-3',
      name: 'Vendor Master',
      system: 'SAP ERP',
      object_type: 'table',
      has_pii: true,
      quality_score: 4,
      fields: [
        { name: 'vendor_id', type: 'string', required: true },
        { name: 'vendor_name', type: 'string', required: true },
        { name: 'payment_terms', type: 'string', required: true },
        { name: 'bank_account', type: 'string', required: true },
        { name: 'status', type: 'string', required: true },
      ],
      metadata: { record_count: 15000 },
    },
    {
      id: 'data-4',
      name: 'GL Accounts',
      system: 'SAP ERP',
      object_type: 'table',
      has_pii: false,
      quality_score: 5,
      fields: [
        { name: 'account_number', type: 'string', required: true },
        { name: 'account_name', type: 'string', required: true },
        { name: 'account_type', type: 'string', required: true },
      ],
      metadata: { record_count: 5000 },
    },
  ],
  
  applications: [
    {
      id: 'app-1',
      name: 'SAP ERP',
      type: 'enterprise',
      vendor: 'SAP',
      auth_type: 'oauth2',
      connectors: [],
      config: { environment: 'production', version: 'S/4HANA' },
    },
    {
      id: 'app-2',
      name: 'DocuSign',
      type: 'saas',
      vendor: 'DocuSign',
      auth_type: 'api_key',
      connectors: [],
      config: { account_id: 'demo-account' },
    },
    {
      id: 'app-3',
      name: 'Microsoft SharePoint',
      type: 'saas',
      vendor: 'Microsoft',
      auth_type: 'oauth2',
      connectors: [],
      config: { site_url: 'https://company.sharepoint.com' },
    },
    {
      id: 'app-4',
      name: 'Email System',
      type: 'saas',
      vendor: 'Microsoft 365',
      auth_type: 'oauth2',
      connectors: [],
      config: { domain: 'company.com' },
    },
  ],
  
  connectors: [
    {
      id: 'conn-1',
      application_id: 'app-1',
      name: 'SAP Invoice API',
      connector_type: 'REST',
      endpoint: 'https://sap-api.company.com/invoices',
      timeout_ms: 30000,
      config: { rate_limit: 100, retry_attempts: 3 },
    },
    {
      id: 'conn-2',
      application_id: 'app-1',
      name: 'SAP PO Lookup API',
      connector_type: 'REST',
      endpoint: 'https://sap-api.company.com/purchase-orders',
      timeout_ms: 30000,
      config: { rate_limit: 100, retry_attempts: 3 },
    },
    {
      id: 'conn-3',
      application_id: 'app-1',
      name: 'SAP Vendor API',
      connector_type: 'REST',
      endpoint: 'https://sap-api.company.com/vendors',
      timeout_ms: 30000,
      config: { rate_limit: 100, retry_attempts: 3 },
    },
    {
      id: 'conn-4',
      application_id: 'app-2',
      name: 'DocuSign Approval Flow',
      connector_type: 'REST',
      endpoint: 'https://api.docusign.com/v2/envelopes',
      timeout_ms: 45000,
      config: { webhook_enabled: true },
    },
    {
      id: 'conn-5',
      application_id: 'app-3',
      name: 'SharePoint Document Upload',
      connector_type: 'REST',
      endpoint: 'https://company.sharepoint.com/_api/web/folders',
      timeout_ms: 60000,
      config: { folder_path: '/Invoices/Archive' },
    },
    {
      id: 'conn-6',
      application_id: 'app-4',
      name: 'Email Invoice Retrieval',
      connector_type: 'IMAP',
      endpoint: 'imap.office365.com',
      timeout_ms: 30000,
      config: { mailbox: 'ap-invoices@company.com', folder: 'Inbox' },
    },
  ],
  
  rules: [
    {
      id: 'rule-1',
      name: 'PO Match Required',
      description: 'Invoice must match an approved purchase order',
      category: 'validation',
      expression: 'invoice.po_number EXISTS IN purchase_orders AND purchase_orders.status = "APPROVED"',
    },
    {
      id: 'rule-2',
      name: 'Amount Tolerance Check',
      description: 'Invoice amount must be within 5% of PO amount',
      category: 'validation',
      expression: 'ABS(invoice.amount - po.amount) / po.amount <= 0.05',
    },
    {
      id: 'rule-3',
      name: 'Vendor Active Status',
      description: 'Vendor must be active in the system',
      category: 'validation',
      expression: 'vendor.status = "ACTIVE" AND vendor.blocked = false',
    },
    {
      id: 'rule-4',
      name: 'Duplicate Invoice Check',
      description: 'Invoice number must be unique for the vendor',
      category: 'validation',
      expression: 'COUNT(invoices WHERE vendor_id = invoice.vendor_id AND invoice_number = invoice.invoice_number) = 0',
    },
    {
      id: 'rule-5',
      name: 'High Value Approval',
      description: 'Invoices over $10,000 require accountant approval',
      category: 'approval',
      expression: 'IF invoice.amount > 10000 THEN requires_approval = true',
    },
    {
      id: 'rule-6',
      name: 'Payment Terms Validation',
      description: 'Payment terms must match vendor master data',
      category: 'validation',
      expression: 'invoice.payment_terms = vendor.payment_terms',
    },
    {
      id: 'rule-7',
      name: 'GL Account Assignment',
      description: 'All line items must have valid GL account codes',
      category: 'validation',
      expression: 'ALL(invoice.line_items, item.gl_account EXISTS IN gl_accounts)',
    },
  ],
  
  slas: [
    {
      id: 'sla-1',
      metric: 'Invoice Processing Time',
      threshold: '24',
      unit: 'hours',
      window: 'from receipt to posting',
    },
    {
      id: 'sla-2',
      metric: 'Exception Resolution Time',
      threshold: '4',
      unit: 'hours',
      window: 'from exception creation to resolution',
    },
    {
      id: 'sla-3',
      metric: 'Approval Turnaround',
      threshold: '2',
      unit: 'hours',
      window: 'during business hours',
    },
    {
      id: 'sla-4',
      metric: 'Payment Accuracy',
      threshold: '99.5',
      unit: 'percent',
      window: 'monthly',
    },
  ],
  
  metrics: {
    baseline_volume: 500,
    avg_handling_time_minutes: 25,
    fte_cost_per_hour: 35,
    error_rate: 0.08,
    breach_cost_usd: 15000,
    updated_at: new Date().toISOString(),
  },
  
  exportedAt: new Date().toISOString(),
  version: '1.0',
};
